# Project Pruner Configuration

# Archive settings
archive:
  compression: xz  # Compression algorithm (xz, gz)
  compression_level: 3  # Compression level (1-9)
  # archive_dir: ~/.projectpruner/archives  # Archive storage directory
  archive_dir: ~/sites/archives  # Archive storage directory
  date_format: "%Y-%m-%d"  # Date format for archive names

# Cleaning settings
clean:
  patterns:  # Patterns to clean
    - "**/node_modules"
    - "**/vendor"
    - "**/dist"
    - "**/build"
    - "**/__pycache__"
    - "**/*.pyc"
    - "**/*.pyo"
    - "**/*.pyd"
    - "**/.DS_Store"
    - "**/Thumbs.db"

  exclude_patterns:  # Patterns to exclude from cleaning
    - "**/node_modules/.bin"
    - "**/vendor/bin"

  min_size: 0  # Minimum file size to clean (in bytes)

# Search settings
search_paths:  # Directories to search for projects
  - ~/projects
  - ~/workspace
  - ~/code
  - ~/sites/test

exclude_paths:  # Directories to exclude from search
  - ~/projects/archive
  - ~/sites/archives
  - ~/workspace/archive

# Logging settings
log_level: INFO  # Log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
log_file: ~/.projectpruner/projectpruner.log  # Log file path
